# Before We Start: The Mathematics of Probilistic Machine Learning

[Daniel Emaasit](http://www.danielemaasit.com/) is a Data Scientist at [Haystax Technology](https://www.haystax.com). His interests involve developing principled [probabilistic models](http://mlg.eng.cam.ac.uk/zoubin/bayesian.html) for problems where training data are scarce by leveraging knowledge from subject-matter experts and context information. In particular, he is interested in [flexible](http://mlg.eng.cam.ac.uk/pub/topics/#np) [probabilistic machine learning](http://mlg.eng.cam.ac.uk/zoubin/bayesian.html) methods, such as Gaussian processes and Dirichlet processes, and data-efficient learning methods such as [Bayesian optimization](https://arxiv.org/abs/1012.2599) & [Model-based Reinforcement Learning](https://arxiv.org/abs/1706.06491).

He is also a Ph.D. Candidate of Transportation Engineering at [UNLV](http://www.unlv.edu/) where his research in [nonparametric Bayesian](http://mlg.eng.cam.ac.uk/pub/topics/#np) methods is focused on developing flexible-statistical models for traveler-behavior analytics.

